### ISSUE TITLE
How to download the desktop application

### ISSUE THREAD

**Issue by cpwnd** [CUAHSI/HydroDesktop#221]
Hey,

I tried to download the HydroDesktop App, but only found the source zip file
which has a size of 1.2 GB and in order to get the app I have to build it from the sources.
http://hydrodesktop.codeplex.com

All the links I could find on other pages, point to the codeplex page, which happens to contain
only the sources.
https://github.com/CUAHSI/HydroDesktop/wiki/Getting-HydroDesktop

Is there a way to download the app, without building it from the source files?

Thanks
Chris

**Comment by martinseul** [comment]
We added the latest executable to the website, as Codeplex is shutting down and removed the download link. You can get it from here: https://www.cuahsi.org/data-models/legacy-tools go to section hydrodesktop. I also added the installer to the release section of the code tab.

Thanks Martin

**Comment by cpwnd** [comment]
Great! Works fine!
Thanks again
